### ISSUE TITLE
Add the data retrieval date at the very top

### ISSUE THREAD

**Issue by dpetronijevic** [sashaobucina/coronatracker#3]
Now, the main title states only: "Most Impacted Countries (by # of confirmed cases)" and there is no obvious information about the freshness of the data. Only when pointing to the right edge of the graph it shows the date of the last data point.
It would be much more informative if the main title contained the date, as for example:
"Most Impacted Countries as of May 5, 2020 (by # of confirmed cases)"
That would also provide the immediate assurance to the visitor that site is up to date.

**Comment by sashaobucina** [comment]
I agree, this is a much clearer approach. The main page will include your suggested solution, and also any other graphs or tables where the last updated date is not obvious for a more consistent view.

Thank you for bringing this to my attention!
